repos:
    - repo: https://github.com/python/black
      rev: 22.6.0
      hooks:
      - id: black
        language_version: python3
        args: [--config, backend/pyproject.toml]
    - repo: https://github.com/timothycrosley/isort
      rev: 5.10.1
      hooks:
      - id: isort
        language_version: python3
        args: [--settings-path, backend/.isort.cfg]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 4.0.1
      hooks:
      - id: flake8
        language_version: python3
        args: [--config, backend/.flake8]
