version: "3.5"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: /start.sh
    restart: on-failure
    env_file: .env
    ports:
        - "8000:8000"
