[tool.black]
line-length = 120
target_version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | _build
    | build
    | dist
  )/
)
'''

[tool.coverage]
    [tool.coverage.run]
    include = ['apps/*']
    relative_files = true

    [tool.coverage.report]
    exclude_lines = [
        'pragma: no cover',

        # Don't complain about missing debug-only code:
        'def __repr__',
        'if self.debug',

        # Don't complain if tests don't hit defensive assertion code:
        'raise AssertionError',
        'raise NotImplementedError',
        'except ImportError',

        # Don't complain if non-runnable code isn't run:
        'if 0:',
        'if __name__ == __main__:'
    ]
    omit = [
        'config/*',
        '*/migrations/*',
        '*/tests/*',
    ]
    precision = 2

    [tool.coverage.html]
    directory = 'htmlcov/'