# Generated by Django 4.0.6 on 2022-09-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"default_related_name": "events", "ordering": ("date",)},
        ),
    ]
